import random

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
from torchmetrics.image import StructuralSimilarityIndexMeasure

from dataset import HipMRIStudyDataset, HipMRIStudyTransforms
from modules import VQVAE


# Device configuration ========================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('cuda' if torch.cuda.is_available() else 'cpu')


# Reproducibility =============================================================
manualSeed = 3
random.seed(manualSeed)
torch.manual_seed(manualSeed)
torch.use_deterministic_algorithms(True)


# Training hyperparameters ====================================================
batch_size = 16
learning_rate = 3e-4
beta = 0.2  # commitment loss scalar.
num_epochs = 101


# Load train and set dataset ==================================================
train_set = HipMRIStudyDataset("/home/groups/comp3710/HipMRI_Study_open/keras_slices_data/keras_slices_train",
                               transform=HipMRIStudyTransforms)
train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)

test_set = HipMRIStudyDataset("/home/groups/comp3710/HipMRI_Study_open/keras_slices_data/keras_slices_test",
                              transform=HipMRIStudyTransforms)
test_loader = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=False)


# Plot Generation =============================================================
def plot_sample_vs_reconstructions(imgs: torch.Tensor, recon_images: torch.Tensor, title: str, file_name: str,
                                   num_samples=5) -> None:
    """
    Plots sample images vs reconstructions and saves.

    :param imgs: Tensor containing the sample images.
    :param recon_images: Tensor containing the reconstructed images.
    :param title: The plot title.
    :param file_name: The plot file name.
    :param num_samples: The number of samples and reconstructions to plot. Must be less than or equal to the number
                        of samples in imgs.
    :return:
    """

    fig, axes = plt.subplots(2, num_samples, figsize=(num_samples*2, 4))
    for i in range(num_samples):
        # Original
        axes[0, i].imshow(imgs[i].cpu().squeeze(), cmap='gray')
        axes[0, i].axis('off')
        if i == 0:
            axes[0, i].set_ylabel('Original', fontsize=12)

        # Reconstructed
        axes[1, i].imshow(recon_images[i].cpu().squeeze(), cmap='gray')
        axes[1, i].axis('off')
        if i == 0:
            axes[1, i].set_ylabel('Reconstructed', fontsize=12)

    plt.suptitle(title, fontsize=14)
    plt.tight_layout()

    # Save
    plt.savefig(file_name)

    # Clean up
    plt.close()

def plot_train_progress(model: VQVAE, epoch: int, ssim: StructuralSimilarityIndexMeasure) -> None:
    """
    Plots a sample of 10 data points from the train set along with reconstructions generated by model. Also displays the
    SSIM index of one batch of reconstructions from the train set. Debug prints the number of unique codes used
    by the vector quantiser.

    :param model: VQVAE model currently being trained.
    :param epoch: The current number of training epoch.
    :param ssim: Structural Similarity Index Measure metric measurer.
    """

    model.eval()  # Place model in evaluation mode.
    with torch.no_grad():
        # Get a batch of data from the training set.
        imgs = next(iter(train_loader))
        imgs = imgs.to(device)

        # Forward pass the sample batch through the model to get reconstructions.
        recon_images, _, _ = model(imgs, disp_unique=True)

        # Calculate the structured similarity between the source images and the reconstructions.
        ssim_batch_value = ssim(recon_images, imgs)

        # Plot samples vs reconstructed.
        plt_title = f'Sample Of VQ-VAE Reconstructions (Train Set - Epoch {epoch}) Batch SSIM={ssim_batch_value:.4f}'
        file_title = f"plots/train-{epoch}.png"
        plot_sample_vs_reconstructions(imgs, recon_images, plt_title, file_title)


def plot_losses(total_losses: list[float], recon_losses: list[float], commit_losses: list[float],
                codebook_losses: list[float]) -> None:
    """
    Plot training losses and save.
    :param total_losses: Sums of recon, commit, and codebook losses.
    :param recon_losses: Reconstruction losses.
    :param commit_losses: Commitment losses.
    :param codebook_losses: Codebook losses.
    """

    # Generate x-axis.
    xs = np.linspace(0, len(total_losses), len(total_losses))
    plt.figure()  # create new plot.

    # Add each type of loss to the plot.
    plt.plot(xs, total_losses, label="Total Loss")
    plt.plot(xs, recon_losses, label="Reconstruction Loss")
    plt.plot(xs, commit_losses, label="Commitment Loss")
    plt.plot(xs, codebook_losses, label="Codebook Loss")

    # Labels and legend.
    plt.xlabel("Batch")
    plt.ylabel("Loss")
    plt.title("Batch vs Loss")
    plt.legend()

    # Save
    plt.savefig("plots/loss.png")

    # Clean up.
    plt.close()

# Model Evaluation ============================================================
def evaluate_model(model: VQVAE, ssim: StructuralSimilarityIndexMeasure) -> None:
    """
    Evaluate the model on the test set. Reporting the average SSIM across all test datapoints as well as plotting a
    sample of test datapoints against their reconstructions.

    :param model: The model to evaluate.
    :param ssim: Structural Similarity Index Measure metric measurer.
    """

    total_test_ssim = 0.0
    test_batches = 0
    total_test_loss = 0.0
    model.eval()  # Ensure model is in evaluation mode.
    print("Evaluating Model On Test Set")
    with torch.no_grad():
        for batch_idx, imgs in enumerate(test_loader):
            imgs = imgs.to(device)
            recon_images, _, _ = model(imgs)

            # Accumulate batch SSIM.
            total_test_ssim += ssim(recon_images, imgs)

            # Accumulate batch reconstruction loss.
            total_test_loss += nn.functional.l1_loss(recon_images, imgs)

            if test_batches == 0:
                plt_title = f'Sample Of VQ-VAE Reconstructions (Test Set) Batch SSIM={total_test_ssim:.4f}'
                file_name = "plots/test.png"
                plot_sample_vs_reconstructions(imgs, recon_images, plt_title, file_name)

            test_batches += 1

        avg_ssim = total_test_ssim / test_batches
        print(f"Average test SSIM: {avg_ssim:.4f}")

        avg_loss = total_test_loss / test_batches
        print(f"Average test reconstruction loss: {avg_loss:.4f}")


# Training loop ===============================================================
def train_model() -> None:
    """
    Train a VQ-VAE on the training dataset, incrementally outputting loss values and plots of progress.
    Once training has completed, evaluate model on the test set and print reconstruction loss as well as SSIM. Also
    plot samples from the test set against reconstructions.
    """

    model = VQVAE().to(device)
    optimiser = torch.optim.Adam(model.parameters(), lr=learning_rate)
    ssim = StructuralSimilarityIndexMeasure(data_range=1.0).to(device)

    total_losses = []
    recon_losses = []
    commit_losses = []
    codebook_losses = []

    # Training loop.
    for epoch in range(num_epochs):
        for (batch_idx, images) in enumerate(train_loader):
            model.train()  # Ensure model is in training mode.

            # Send data to device.
            images = images.to(device)

            # Forward pass
            recon, commitment_loss, codebook_loss = model(images)

            # Calculate reconstruction loss and overall loss
            recon_loss = nn.functional.l1_loss(recon, images)
            loss = recon_loss + (beta * commitment_loss) + codebook_loss

            # Reset model gradients.
            optimiser.zero_grad()

            # Backward pass.
            loss.backward()

            # Update model.
            optimiser.step()

            # Track losses.
            total_losses.append(loss.item())
            recon_losses.append(recon_loss.item())
            commit_losses.append(beta * commitment_loss.item())
            codebook_losses.append(codebook_loss.item())

            # Print status every twenty batches.
            if batch_idx % 20 == 0:
                print(
                    f"Epoch {epoch} Batch {batch_idx}: \t Loss: {loss.item():.4f} \t "
                    f"Recon Loss: {recon_loss.item():.4f} \t Commitment Loss: {beta * commitment_loss.item():.4f} \t "
                    f"Codebook Loss: {codebook_loss.item():.4f}"
                )

        # Every fifth epoch (or every epoch for the first five) plot and save a sample of training data and
        # reconstructions to visualise training progress.
        if epoch % 5 == 0 or epoch < 5:
            plot_train_progress(model, epoch, ssim)

    # Save model to a file. This is done before any operations involving the test set are performed.
    torch.save(model, "vq-vae.model")

    # Training complete, now evaluate using test set.
    evaluate_model(model, ssim)

    # Plot training losses.
    plot_losses(total_losses, recon_losses, commit_losses, codebook_losses)

# If script is run, train model ===============================================
if __name__ == "__main__":
    train_model()
